/* Walkin v1.0
 * Hotel Management Software
 * FC Solutions - Software Division
 * 22/Feb/2010
 * Azores
 */
package walkin;

import org.jdesktop.application.Action;

/**
 */
public class formSystemConfig extends javax.swing.JFrame {

    /** Creates new form formSystemConfig */
    public formSystemConfig() {
        initComponents();
    }

    /** Action to quit form. */
    @Action
    public void cancelButtonAction() {
        dispose();
    }

    /**
     * initComponents
     * Initialization/building of Swing components and layout.
     * WARNING: DD NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPanel = new javax.swing.JTabbedPane();
        generalTab = new javax.swing.JPanel();
        usersTab = new javax.swing.JPanel();
        usersSymbolLabel = new javax.swing.JLabel();
        usersTableLabel = new javax.swing.JLabel();
        usersScrollTable = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        removeButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        usersTabDescriptionLabel = new javax.swing.JLabel();
        aspectTab = new javax.swing.JPanel();
        lookAndFellPanel = new javax.swing.JPanel();
        lookAndFeelLabel = new javax.swing.JLabel();
        lookAndFeelCombobox = new javax.swing.JComboBox();
        fontLabel = new javax.swing.JLabel();
        fontCombobox = new javax.swing.JComboBox();
        applyButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        systemConfigSymbolLabel = new javax.swing.JLabel();
        systemConfigTitleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("walkin/resources/Main"); // NOI18N
        setTitle(bundle.getString("Application.name")); // NOI18N
        setName("Form"); // NOI18N

        tabbedPanel.setName("tabbedPanel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(walkin.Main.class).getContext().getResourceMap(formSystemConfig.class);
        generalTab.setBackground(resourceMap.getColor("generalTab.background")); // NOI18N
        generalTab.setName("generalTab"); // NOI18N

        javax.swing.GroupLayout generalTabLayout = new javax.swing.GroupLayout(generalTab);
        generalTab.setLayout(generalTabLayout);
        generalTabLayout.setHorizontalGroup(
            generalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );
        generalTabLayout.setVerticalGroup(
            generalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );

        tabbedPanel.addTab(resourceMap.getString("generalTab.TabConstraints.tabTitle"), generalTab); // NOI18N

        usersTab.setBackground(resourceMap.getColor("usersTab.background")); // NOI18N
        usersTab.setName("usersTab"); // NOI18N

        usersSymbolLabel.setIcon(resourceMap.getIcon("usersSymbolLabel.icon")); // NOI18N
        usersSymbolLabel.setText(resourceMap.getString("usersSymbolLabel.text")); // NOI18N
        usersSymbolLabel.setName("usersSymbolLabel"); // NOI18N

        usersTableLabel.setText(resourceMap.getString("usersTableLabel.text")); // NOI18N
        usersTableLabel.setName("usersTableLabel"); // NOI18N

        usersScrollTable.setName("usersScrollTable"); // NOI18N

        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Grupo", "Observações"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        usersTable.setName("usersTable"); // NOI18N
        usersScrollTable.setViewportView(usersTable);

        removeButton.setText(resourceMap.getString("removeButton.text")); // NOI18N
        removeButton.setName("removeButton"); // NOI18N

        addButton.setText(resourceMap.getString("addButton.text")); // NOI18N
        addButton.setName("addButton"); // NOI18N

        usersTabDescriptionLabel.setText(resourceMap.getString("usersTabDescriptionLabel.text")); // NOI18N
        usersTabDescriptionLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        usersTabDescriptionLabel.setName("usersTabDescriptionLabel"); // NOI18N

        javax.swing.GroupLayout usersTabLayout = new javax.swing.GroupLayout(usersTab);
        usersTab.setLayout(usersTabLayout);
        usersTabLayout.setHorizontalGroup(
            usersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usersTabLayout.createSequentialGroup()
                        .addComponent(usersSymbolLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usersTabDescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE))
                    .addComponent(usersTableLabel)
                    .addComponent(usersScrollTable, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usersTabLayout.createSequentialGroup()
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeButton)))
                .addContainerGap())
        );
        usersTabLayout.setVerticalGroup(
            usersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usersSymbolLabel)
                    .addComponent(usersTabDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(usersTableLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usersScrollTable, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(usersTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeButton)
                    .addComponent(addButton))
                .addGap(0, 0, 0))
        );

        tabbedPanel.addTab(resourceMap.getString("usersTab.TabConstraints.tabTitle"), usersTab); // NOI18N

        aspectTab.setBackground(resourceMap.getColor("aspectTab.background")); // NOI18N
        aspectTab.setName("aspectTab"); // NOI18N

        lookAndFellPanel.setBackground(resourceMap.getColor("lookAndFellPanel.background")); // NOI18N
        lookAndFellPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), resourceMap.getString("lookAndFellPanel.border.title"))); // NOI18N
        lookAndFellPanel.setName("lookAndFellPanel"); // NOI18N

        lookAndFeelLabel.setText(resourceMap.getString("lookAndFeelLabel.text")); // NOI18N
        lookAndFeelLabel.setName("lookAndFeelLabel"); // NOI18N

        lookAndFeelCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        lookAndFeelCombobox.setName("lookAndFeelCombobox"); // NOI18N

        fontLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fontLabel.setText(resourceMap.getString("fontLabel.text")); // NOI18N
        fontLabel.setName("fontLabel"); // NOI18N

        fontCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        fontCombobox.setName("fontCombobox"); // NOI18N

        javax.swing.GroupLayout lookAndFellPanelLayout = new javax.swing.GroupLayout(lookAndFellPanel);
        lookAndFellPanel.setLayout(lookAndFellPanelLayout);
        lookAndFellPanelLayout.setHorizontalGroup(
            lookAndFellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lookAndFellPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lookAndFellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(fontLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lookAndFeelLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lookAndFellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fontCombobox, 0, 319, Short.MAX_VALUE)
                    .addComponent(lookAndFeelCombobox, 0, 319, Short.MAX_VALUE))
                .addContainerGap())
        );
        lookAndFellPanelLayout.setVerticalGroup(
            lookAndFellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lookAndFellPanelLayout.createSequentialGroup()
                .addGroup(lookAndFellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lookAndFeelLabel)
                    .addComponent(lookAndFeelCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lookAndFellPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fontLabel)
                    .addComponent(fontCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout aspectTabLayout = new javax.swing.GroupLayout(aspectTab);
        aspectTab.setLayout(aspectTabLayout);
        aspectTabLayout.setHorizontalGroup(
            aspectTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aspectTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lookAndFellPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        aspectTabLayout.setVerticalGroup(
            aspectTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aspectTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lookAndFellPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        tabbedPanel.addTab(resourceMap.getString("aspectTab.TabConstraints.tabTitle"), aspectTab); // NOI18N

        applyButton.setText(resourceMap.getString("applyButton.text")); // NOI18N
        applyButton.setName("applyButton"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(walkin.Main.class).getContext().getActionMap(formSystemConfig.class, this);
        cancelButton.setAction(actionMap.get("cancelButtonAction")); // NOI18N
        cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N

        okButton.setText(resourceMap.getString("okButton.text")); // NOI18N
        okButton.setName("okButton"); // NOI18N

        systemConfigSymbolLabel.setIcon(resourceMap.getIcon("systemConfigSymbolLabel.icon")); // NOI18N
        systemConfigSymbolLabel.setText(resourceMap.getString("systemConfigSymbolLabel.text")); // NOI18N
        systemConfigSymbolLabel.setName("systemConfigSymbolLabel"); // NOI18N

        systemConfigTitleLabel.setFont(resourceMap.getFont("systemConfigTitleLabel.font")); // NOI18N
        systemConfigTitleLabel.setText(resourceMap.getString("systemConfigTitleLabel.text")); // NOI18N
        systemConfigTitleLabel.setName("systemConfigTitleLabel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tabbedPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(systemConfigSymbolLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(systemConfigTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(okButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(applyButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(systemConfigTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(systemConfigSymbolLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(applyButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton applyButton;
    private javax.swing.JPanel aspectTab;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox fontCombobox;
    private javax.swing.JLabel fontLabel;
    private javax.swing.JPanel generalTab;
    private javax.swing.JComboBox lookAndFeelCombobox;
    private javax.swing.JLabel lookAndFeelLabel;
    private javax.swing.JPanel lookAndFellPanel;
    private javax.swing.JButton okButton;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel systemConfigSymbolLabel;
    private javax.swing.JLabel systemConfigTitleLabel;
    private javax.swing.JTabbedPane tabbedPanel;
    private javax.swing.JScrollPane usersScrollTable;
    private javax.swing.JLabel usersSymbolLabel;
    private javax.swing.JPanel usersTab;
    private javax.swing.JLabel usersTabDescriptionLabel;
    private javax.swing.JTable usersTable;
    private javax.swing.JLabel usersTableLabel;
    // End of variables declaration//GEN-END:variables
}
