/* Walkin v1.0
 * Hotel Management Software
 * FC Solutions - Software Division
 * 22/Feb/2010
 * Azores
 */
package walkin;

import org.jdesktop.application.Action;

/**
 */
public class formHotelConfig extends javax.swing.JFrame {

    /** Creates new form formHotelConfig */
    public formHotelConfig() {
        initComponents();
    }

    /** Action to quit form. */
    @Action
    public void cancelButtonAction() {
        dispose();
    }

    /**
     * initComponents
     * Initialization/building of Swing components and layout.
     * WARNING: DD NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPanel = new javax.swing.JTabbedPane();
        generalTab = new javax.swing.JPanel();
        idHotelPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        businessNameLabel = new javax.swing.JLabel();
        taxNumberLabel = new javax.swing.JLabel();
        capitalLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        zipCodeLabel = new javax.swing.JLabel();
        countryLabel = new javax.swing.JLabel();
        hotelLevelLabel = new javax.swing.JLabel();
        directorNameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        businessNameTextField = new javax.swing.JTextField();
        taxNumberTextField = new javax.swing.JTextField();
        capitalTextField = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        cityTextField = new javax.swing.JTextField();
        zipCodeTextField = new javax.swing.JTextField();
        countryCombobox = new javax.swing.JComboBox();
        hotelLevelCombobox = new javax.swing.JComboBox();
        directorNameTextField = new javax.swing.JTextField();
        hotelSymbolLabel = new javax.swing.JLabel();
        generalTabDescriptionLabel = new javax.swing.JLabel();
        contactsTab = new javax.swing.JPanel();
        generalContactPanel = new javax.swing.JPanel();
        contactTableScroll = new javax.swing.JScrollPane();
        contactTable = new javax.swing.JTable();
        removeContactButton = new javax.swing.JButton();
        addContactButton = new javax.swing.JButton();
        contactsSymbolLabel = new javax.swing.JLabel();
        contactTabDescriptionLabel = new javax.swing.JLabel();
        roomsTab = new javax.swing.JPanel();
        roomKindPanel = new javax.swing.JPanel();
        roomKindTableScroll = new javax.swing.JScrollPane();
        roomKindTable = new javax.swing.JTable();
        roomKindRemoveButton = new javax.swing.JButton();
        roomKindAddButton = new javax.swing.JButton();
        roomSymbolLabel = new javax.swing.JLabel();
        roomTabDescriptionLabel = new javax.swing.JLabel();
        roomPanel = new javax.swing.JPanel();
        roomTableScroll = new javax.swing.JScrollPane();
        roomTable = new javax.swing.JTable();
        roomRemoveButton = new javax.swing.JButton();
        roomAddButton = new javax.swing.JButton();
        servicesTab = new javax.swing.JPanel();
        serviceSymbolLabel = new javax.swing.JLabel();
        serviceTabDescriptionLabel = new javax.swing.JLabel();
        servicePanel = new javax.swing.JPanel();
        serviceTableScroll = new javax.swing.JScrollPane();
        serviceTable = new javax.swing.JTable();
        serviceRemoveButton = new javax.swing.JButton();
        serviceAddButton = new javax.swing.JButton();
        rateTab = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        applyButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        hotelConfigSymbolLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("walkin/resources/Main"); // NOI18N
        setTitle(bundle.getString("Application.name")); // NOI18N
        setName("Form"); // NOI18N

        tabbedPanel.setName("tabbedPanel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(walkin.Main.class).getContext().getResourceMap(formHotelConfig.class);
        generalTab.setBackground(resourceMap.getColor("generalTab.background")); // NOI18N
        generalTab.setName("generalTab"); // NOI18N

        idHotelPanel.setBackground(resourceMap.getColor("idHotelPanel.background")); // NOI18N
        idHotelPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), resourceMap.getString("idHotelPanel.border.title"))); // NOI18N
        idHotelPanel.setName("idHotelPanel"); // NOI18N

        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameLabel.setLabelFor(nameTextField);
        nameLabel.setText(resourceMap.getString("nameLabel.text")); // NOI18N
        nameLabel.setName("nameLabel"); // NOI18N

        businessNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        businessNameLabel.setLabelFor(businessNameTextField);
        businessNameLabel.setText(resourceMap.getString("businessNameLabel.text")); // NOI18N
        businessNameLabel.setName("businessNameLabel"); // NOI18N

        taxNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        taxNumberLabel.setLabelFor(taxNumberTextField);
        taxNumberLabel.setText(resourceMap.getString("taxNumberLabel.text")); // NOI18N
        taxNumberLabel.setName("taxNumberLabel"); // NOI18N

        capitalLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        capitalLabel.setLabelFor(capitalTextField);
        capitalLabel.setText(resourceMap.getString("capitalLabel.text")); // NOI18N
        capitalLabel.setName("capitalLabel"); // NOI18N

        addressLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addressLabel.setLabelFor(addressTextField);
        addressLabel.setText(resourceMap.getString("addressLabel.text")); // NOI18N
        addressLabel.setName("addressLabel"); // NOI18N

        cityLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cityLabel.setLabelFor(cityTextField);
        cityLabel.setText(resourceMap.getString("cityLabel.text")); // NOI18N
        cityLabel.setName("cityLabel"); // NOI18N

        zipCodeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        zipCodeLabel.setLabelFor(zipCodeTextField);
        zipCodeLabel.setText(resourceMap.getString("zipCodeLabel.text")); // NOI18N
        zipCodeLabel.setName("zipCodeLabel"); // NOI18N

        countryLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        countryLabel.setLabelFor(countryCombobox);
        countryLabel.setText(resourceMap.getString("countryLabel.text")); // NOI18N
        countryLabel.setName("countryLabel"); // NOI18N

        hotelLevelLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hotelLevelLabel.setText(resourceMap.getString("hotelLevelLabel.text")); // NOI18N
        hotelLevelLabel.setName("hotelLevelLabel"); // NOI18N

        directorNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        directorNameLabel.setText(resourceMap.getString("directorNameLabel.text")); // NOI18N
        directorNameLabel.setName("directorNameLabel"); // NOI18N

        nameTextField.setText(resourceMap.getString("nameTextField.text")); // NOI18N
        nameTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        nameTextField.setName("nameTextField"); // NOI18N

        businessNameTextField.setText(resourceMap.getString("businessNameTextField.text")); // NOI18N
        businessNameTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        businessNameTextField.setName("businessNameTextField"); // NOI18N

        taxNumberTextField.setText(resourceMap.getString("taxNumberTextField.text")); // NOI18N
        taxNumberTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        taxNumberTextField.setName("taxNumberTextField"); // NOI18N

        capitalTextField.setText(resourceMap.getString("capitalTextField.text")); // NOI18N
        capitalTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        capitalTextField.setName("capitalTextField"); // NOI18N

        addressTextField.setText(resourceMap.getString("addressTextField.text")); // NOI18N
        addressTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        addressTextField.setName("addressTextField"); // NOI18N

        cityTextField.setText(resourceMap.getString("cityTextField.text")); // NOI18N
        cityTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        cityTextField.setName("cityTextField"); // NOI18N

        zipCodeTextField.setText(resourceMap.getString("zipCodeTextField.text")); // NOI18N
        zipCodeTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        zipCodeTextField.setName("zipCodeTextField"); // NOI18N

        countryCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        countryCombobox.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        countryCombobox.setName("countryCombobox"); // NOI18N

        hotelLevelCombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hotel 2 estrelas", "Hotel 3 estrelas", "Hotel 4 estrelas", "Hotel 5 estrelas", "Apart-Hotel 2 estrelas", "Apart-Hotel 3 estrelas", "Apart-Hotel 4 estrelas", "Apart-Hotel 5 estrelas" }));
        hotelLevelCombobox.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hotelLevelCombobox.setName("hotelLevelCombobox"); // NOI18N

        directorNameTextField.setText(resourceMap.getString("directorNameTextField.text")); // NOI18N
        directorNameTextField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        directorNameTextField.setName("directorNameTextField"); // NOI18N

        javax.swing.GroupLayout idHotelPanelLayout = new javax.swing.GroupLayout(idHotelPanel);
        idHotelPanel.setLayout(idHotelPanelLayout);
        idHotelPanelLayout.setHorizontalGroup(
            idHotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idHotelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idHotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(directorNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hotelLevelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(businessNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(taxNumberLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(capitalLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addressLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cityLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zipCodeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(countryLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(idHotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(businessNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(taxNumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(capitalTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(addressTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(cityTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(zipCodeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(countryCombobox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 340, Short.MAX_VALUE)
                    .addComponent(hotelLevelCombobox, 0, 340, Short.MAX_VALUE)
                    .addComponent(directorNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
                .addContainerGap())
        );
        idHotelPanelLayout.setVerticalGroup(
            idHotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idHotelPanelLayout.createSequentialGroup()
                .addGroup(idHotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(idHotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(businessNameLabel)
                    .addComponent(businessNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(idHotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taxNumberLabel)
                    .addComponent(taxNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(idHotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capitalLabel)
                    .addComponent(capitalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(idHotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(idHotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityLabel)
                    .addComponent(cityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(idHotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zipCodeLabel)
                    .addComponent(zipCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(idHotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countryLabel)
                    .addComponent(countryCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(idHotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hotelLevelLabel)
                    .addComponent(hotelLevelCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(idHotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(directorNameLabel)
                    .addComponent(directorNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        hotelSymbolLabel.setIcon(resourceMap.getIcon("hotelSymbolLabel.icon")); // NOI18N
        hotelSymbolLabel.setText(resourceMap.getString("hotelSymbolLabel.text")); // NOI18N
        hotelSymbolLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        hotelSymbolLabel.setName("hotelSymbolLabel"); // NOI18N

        generalTabDescriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        generalTabDescriptionLabel.setText(resourceMap.getString("generalTabDescriptionLabel.text")); // NOI18N
        generalTabDescriptionLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        generalTabDescriptionLabel.setName("generalTabDescriptionLabel"); // NOI18N

        javax.swing.GroupLayout generalTabLayout = new javax.swing.GroupLayout(generalTab);
        generalTab.setLayout(generalTabLayout);
        generalTabLayout.setHorizontalGroup(
            generalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generalTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idHotelPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(generalTabLayout.createSequentialGroup()
                        .addComponent(hotelSymbolLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(generalTabDescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)))
                .addContainerGap())
        );
        generalTabLayout.setVerticalGroup(
            generalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generalTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hotelSymbolLabel)
                    .addComponent(generalTabDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idHotelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPanel.addTab(resourceMap.getString("generalTab.TabConstraints.tabTitle"), generalTab); // NOI18N

        contactsTab.setBackground(resourceMap.getColor("contactsTab.background")); // NOI18N
        contactsTab.setName("contactsTab"); // NOI18N

        generalContactPanel.setBackground(resourceMap.getColor("generalContactPanel.background")); // NOI18N
        generalContactPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), resourceMap.getString("generalContactPanel.border.title"))); // NOI18N
        generalContactPanel.setName("generalContactPanel"); // NOI18N

        contactTableScroll.setName("contactTableScroll"); // NOI18N

        contactTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Secção", "Telefone", "Fax", "Email", "WebSite"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        contactTable.setName("contactTable"); // NOI18N
        contactTableScroll.setViewportView(contactTable);

        removeContactButton.setText(resourceMap.getString("removeContactButton.text")); // NOI18N
        removeContactButton.setName("removeContactButton"); // NOI18N

        addContactButton.setText(resourceMap.getString("addContactButton.text")); // NOI18N
        addContactButton.setName("addContactButton"); // NOI18N

        javax.swing.GroupLayout generalContactPanelLayout = new javax.swing.GroupLayout(generalContactPanel);
        generalContactPanel.setLayout(generalContactPanelLayout);
        generalContactPanelLayout.setHorizontalGroup(
            generalContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generalContactPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generalContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contactTableScroll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                    .addGroup(generalContactPanelLayout.createSequentialGroup()
                        .addComponent(addContactButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeContactButton)))
                .addContainerGap())
        );
        generalContactPanelLayout.setVerticalGroup(
            generalContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generalContactPanelLayout.createSequentialGroup()
                .addComponent(contactTableScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalContactPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeContactButton)
                    .addComponent(addContactButton))
                .addContainerGap())
        );

        contactsSymbolLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        contactsSymbolLabel.setIcon(resourceMap.getIcon("contactsSymbolLabel.icon")); // NOI18N
        contactsSymbolLabel.setText(resourceMap.getString("contactsSymbolLabel.text")); // NOI18N
        contactsSymbolLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        contactsSymbolLabel.setName("contactsSymbolLabel"); // NOI18N

        contactTabDescriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        contactTabDescriptionLabel.setText(resourceMap.getString("contactTabDescriptionLabel.text")); // NOI18N
        contactTabDescriptionLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        contactTabDescriptionLabel.setName("contactTabDescriptionLabel"); // NOI18N

        javax.swing.GroupLayout contactsTabLayout = new javax.swing.GroupLayout(contactsTab);
        contactsTab.setLayout(contactsTabLayout);
        contactsTabLayout.setHorizontalGroup(
            contactsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contactsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contactsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(generalContactPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contactsTabLayout.createSequentialGroup()
                        .addComponent(contactsSymbolLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contactTabDescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)))
                .addContainerGap())
        );
        contactsTabLayout.setVerticalGroup(
            contactsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contactsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contactTabDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactsSymbolLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generalContactPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPanel.addTab(resourceMap.getString("contactsTab.TabConstraints.tabTitle"), contactsTab); // NOI18N

        roomsTab.setBackground(resourceMap.getColor("roomsTab.background")); // NOI18N
        roomsTab.setName("roomsTab"); // NOI18N

        roomKindPanel.setBackground(resourceMap.getColor("roomKindPanel.background")); // NOI18N
        roomKindPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), resourceMap.getString("roomKindPanel.border.title"))); // NOI18N
        roomKindPanel.setName("roomKindPanel"); // NOI18N

        roomKindTableScroll.setName("roomKindTableScroll"); // NOI18N

        roomKindTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Numero de Camas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        roomKindTable.setName("roomKindTable"); // NOI18N
        roomKindTableScroll.setViewportView(roomKindTable);

        roomKindRemoveButton.setText(resourceMap.getString("roomKindRemoveButton.text")); // NOI18N
        roomKindRemoveButton.setName("roomKindRemoveButton"); // NOI18N

        roomKindAddButton.setText(resourceMap.getString("roomKindAddButton.text")); // NOI18N
        roomKindAddButton.setName("roomKindAddButton"); // NOI18N

        javax.swing.GroupLayout roomKindPanelLayout = new javax.swing.GroupLayout(roomKindPanel);
        roomKindPanel.setLayout(roomKindPanelLayout);
        roomKindPanelLayout.setHorizontalGroup(
            roomKindPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomKindPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roomKindPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roomKindPanelLayout.createSequentialGroup()
                        .addComponent(roomKindAddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roomKindRemoveButton))
                    .addComponent(roomKindTableScroll))
                .addContainerGap())
        );
        roomKindPanelLayout.setVerticalGroup(
            roomKindPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomKindPanelLayout.createSequentialGroup()
                .addComponent(roomKindTableScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roomKindPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomKindRemoveButton)
                    .addComponent(roomKindAddButton)))
        );

        roomSymbolLabel.setIcon(resourceMap.getIcon("roomSymbolLabel.icon")); // NOI18N
        roomSymbolLabel.setText(resourceMap.getString("roomSymbolLabel.text")); // NOI18N
        roomSymbolLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        roomSymbolLabel.setName("roomSymbolLabel"); // NOI18N

        roomTabDescriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        roomTabDescriptionLabel.setText(resourceMap.getString("roomTabDescriptionLabel.text")); // NOI18N
        roomTabDescriptionLabel.setName("roomTabDescriptionLabel"); // NOI18N

        roomPanel.setBackground(resourceMap.getColor("roomPanel.background")); // NOI18N
        roomPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), resourceMap.getString("roomPanel.border.title"))); // NOI18N
        roomPanel.setName("roomPanel"); // NOI18N

        roomTableScroll.setName("roomTableScroll"); // NOI18N

        roomTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Tipo", "Observações"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        roomTable.setName("roomTable"); // NOI18N
        roomTableScroll.setViewportView(roomTable);

        roomRemoveButton.setText(resourceMap.getString("roomRemoveButton.text")); // NOI18N
        roomRemoveButton.setName("roomRemoveButton"); // NOI18N

        roomAddButton.setText(resourceMap.getString("roomAddButton.text")); // NOI18N
        roomAddButton.setName("roomAddButton"); // NOI18N

        javax.swing.GroupLayout roomPanelLayout = new javax.swing.GroupLayout(roomPanel);
        roomPanel.setLayout(roomPanelLayout);
        roomPanelLayout.setHorizontalGroup(
            roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(roomTableScroll)
                    .addGroup(roomPanelLayout.createSequentialGroup()
                        .addComponent(roomAddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roomRemoveButton)))
                .addContainerGap())
        );
        roomPanelLayout.setVerticalGroup(
            roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roomPanelLayout.createSequentialGroup()
                .addComponent(roomTableScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addGroup(roomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomRemoveButton)
                    .addComponent(roomAddButton)))
        );

        javax.swing.GroupLayout roomsTabLayout = new javax.swing.GroupLayout(roomsTab);
        roomsTab.setLayout(roomsTabLayout);
        roomsTabLayout.setHorizontalGroup(
            roomsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roomsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roomsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(roomPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roomKindPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, roomsTabLayout.createSequentialGroup()
                        .addComponent(roomSymbolLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roomTabDescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)))
                .addContainerGap())
        );
        roomsTabLayout.setVerticalGroup(
            roomsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roomsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(roomTabDescriptionLabel)
                    .addComponent(roomSymbolLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roomKindPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPanel.addTab(resourceMap.getString("roomsTab.TabConstraints.tabTitle"), roomsTab); // NOI18N

        servicesTab.setBackground(resourceMap.getColor("servicesTab.background")); // NOI18N
        servicesTab.setName("servicesTab"); // NOI18N

        serviceSymbolLabel.setIcon(resourceMap.getIcon("serviceSymbolLabel.icon")); // NOI18N
        serviceSymbolLabel.setText(resourceMap.getString("serviceSymbolLabel.text")); // NOI18N
        serviceSymbolLabel.setName("serviceSymbolLabel"); // NOI18N

        serviceTabDescriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        serviceTabDescriptionLabel.setText(resourceMap.getString("serviceTabDescriptionLabel.text")); // NOI18N
        serviceTabDescriptionLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        serviceTabDescriptionLabel.setName("serviceTabDescriptionLabel"); // NOI18N

        servicePanel.setBackground(resourceMap.getColor("servicePanel.background")); // NOI18N
        servicePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), resourceMap.getString("servicePanel.border.title"))); // NOI18N
        servicePanel.setName("servicePanel"); // NOI18N

        serviceTableScroll.setName("serviceTableScroll"); // NOI18N

        serviceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        serviceTable.setName("serviceTable"); // NOI18N
        serviceTableScroll.setViewportView(serviceTable);

        serviceRemoveButton.setText(resourceMap.getString("serviceRemoveButton.text")); // NOI18N
        serviceRemoveButton.setName("serviceRemoveButton"); // NOI18N

        serviceAddButton.setText(resourceMap.getString("serviceAddButton.text")); // NOI18N
        serviceAddButton.setName("serviceAddButton"); // NOI18N

        javax.swing.GroupLayout servicePanelLayout = new javax.swing.GroupLayout(servicePanel);
        servicePanel.setLayout(servicePanelLayout);
        servicePanelLayout.setHorizontalGroup(
            servicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, servicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(servicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(serviceTableScroll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                    .addGroup(servicePanelLayout.createSequentialGroup()
                        .addComponent(serviceAddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serviceRemoveButton)))
                .addContainerGap())
        );
        servicePanelLayout.setVerticalGroup(
            servicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, servicePanelLayout.createSequentialGroup()
                .addComponent(serviceTableScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(servicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serviceRemoveButton)
                    .addComponent(serviceAddButton)))
        );

        javax.swing.GroupLayout servicesTabLayout = new javax.swing.GroupLayout(servicesTab);
        servicesTab.setLayout(servicesTabLayout);
        servicesTabLayout.setHorizontalGroup(
            servicesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, servicesTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(servicesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(servicePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(servicesTabLayout.createSequentialGroup()
                        .addComponent(serviceSymbolLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serviceTabDescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)))
                .addContainerGap())
        );
        servicesTabLayout.setVerticalGroup(
            servicesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(servicesTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(servicesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(serviceTabDescriptionLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serviceSymbolLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(servicePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPanel.addTab(resourceMap.getString("servicesTab.TabConstraints.tabTitle"), servicesTab); // NOI18N

        rateTab.setBackground(resourceMap.getColor("rateTab.background")); // NOI18N
        rateTab.setName("rateTab"); // NOI18N

        jLabel2.setIcon(resourceMap.getIcon("jLabel2.icon")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout rateTabLayout = new javax.swing.GroupLayout(rateTab);
        rateTab.setLayout(rateTabLayout);
        rateTabLayout.setHorizontalGroup(
            rateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rateTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(462, Short.MAX_VALUE))
        );
        rateTabLayout.setVerticalGroup(
            rateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rateTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(366, Short.MAX_VALUE))
        );

        tabbedPanel.addTab(resourceMap.getString("rateTab.TabConstraints.tabTitle"), rateTab); // NOI18N

        applyButton.setText(resourceMap.getString("applyButton.text")); // NOI18N
        applyButton.setName("applyButton"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(walkin.Main.class).getContext().getActionMap(formHotelConfig.class, this);
        cancelButton.setAction(actionMap.get("cancelButtonAction")); // NOI18N
        cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N

        okButton.setText(resourceMap.getString("okButton.text")); // NOI18N
        okButton.setName("okButton"); // NOI18N

        hotelConfigSymbolLabel.setIcon(resourceMap.getIcon("hotelConfigSymbolLabel.icon")); // NOI18N
        hotelConfigSymbolLabel.setText(resourceMap.getString("hotelConfigSymbolLabel.text")); // NOI18N
        hotelConfigSymbolLabel.setName("hotelConfigSymbolLabel"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tabbedPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(applyButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(hotelConfigSymbolLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hotelConfigSymbolLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(applyButton, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addContactButton;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JButton applyButton;
    private javax.swing.JLabel businessNameLabel;
    private javax.swing.JTextField businessNameTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel capitalLabel;
    private javax.swing.JTextField capitalTextField;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JLabel contactTabDescriptionLabel;
    private javax.swing.JTable contactTable;
    private javax.swing.JScrollPane contactTableScroll;
    private javax.swing.JLabel contactsSymbolLabel;
    private javax.swing.JPanel contactsTab;
    private javax.swing.JComboBox countryCombobox;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JLabel directorNameLabel;
    private javax.swing.JTextField directorNameTextField;
    private javax.swing.JPanel generalContactPanel;
    private javax.swing.JPanel generalTab;
    private javax.swing.JLabel generalTabDescriptionLabel;
    private javax.swing.JLabel hotelConfigSymbolLabel;
    private javax.swing.JComboBox hotelLevelCombobox;
    private javax.swing.JLabel hotelLevelLabel;
    private javax.swing.JLabel hotelSymbolLabel;
    private javax.swing.JPanel idHotelPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel rateTab;
    private javax.swing.JButton removeContactButton;
    private javax.swing.JButton roomAddButton;
    private javax.swing.JButton roomKindAddButton;
    private javax.swing.JPanel roomKindPanel;
    private javax.swing.JButton roomKindRemoveButton;
    private javax.swing.JTable roomKindTable;
    private javax.swing.JScrollPane roomKindTableScroll;
    private javax.swing.JPanel roomPanel;
    private javax.swing.JButton roomRemoveButton;
    private javax.swing.JLabel roomSymbolLabel;
    private javax.swing.JLabel roomTabDescriptionLabel;
    private javax.swing.JTable roomTable;
    private javax.swing.JScrollPane roomTableScroll;
    private javax.swing.JPanel roomsTab;
    private javax.swing.JButton serviceAddButton;
    private javax.swing.JPanel servicePanel;
    private javax.swing.JButton serviceRemoveButton;
    private javax.swing.JLabel serviceSymbolLabel;
    private javax.swing.JLabel serviceTabDescriptionLabel;
    private javax.swing.JTable serviceTable;
    private javax.swing.JScrollPane serviceTableScroll;
    private javax.swing.JPanel servicesTab;
    private javax.swing.JTabbedPane tabbedPanel;
    private javax.swing.JLabel taxNumberLabel;
    private javax.swing.JTextField taxNumberTextField;
    private javax.swing.JLabel zipCodeLabel;
    private javax.swing.JTextField zipCodeTextField;
    // End of variables declaration//GEN-END:variables
}
